    type: web
    name: gamehost
    runtime: static
    buildCommand: npm install
    staticPublishPath: ./
    previews:
      generation: automatic
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a